{% set name = "spreg" %}
{% set version = "1.8.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pysal/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c6a6ffcd348d578cfea72e7e083fe6ff77085d4a779d16f91928ccbf08b5e52

build:
  number: 0
  # increase min python version to 310, where in which we are able to use
  # libpysal version >=4.8. More info in libpysal comment.
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - toml
    - wheel
  run:
    - python
    # introduce upper bound:
    # spreg/tests/test_sputils.py::Test_Sparse_Utils::test_multiply - AssertionError: <Compressed Sparse Row sparse matrix of dtype 'float64'
	  # with 7 stored elements and shape (20, 20)> is not an instance of <class 'scipy.sparse._csc.csc_matrix'>
    - scipy >=0.11,<1.16  # [py>=310]
    - scipy >=0.11,<1.12  # [py<310]
    - numpy >=1.23
    - pandas
    # upstream pins to 4.0.0; increase min bound to 4.8.0 where graphs APIs (used
    # by this package) was introduced to libpysal
    - libpysal >=4.8.0  #  [py>=310]
    - scikit-learn >=0.22

{% set deselect_tests = "" %}

# tolerance error: Not equal to tolerance rtol=1e-07, atol=0
{% set deselect_tests = deselect_tests + " --deselect=spreg/tests/test_ml_error_regimes.py::TestMLError::test_model2" %} # [py<310 or (osx and x86_64)]

test:
  imports:
    - spreg
  requires:
    - pip
    - pytest
    - geopandas
  source_files:
    # tests not in the wheel
    - spreg/tests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv {{ deselect_tests }}

about:
  home: https://github.com/pysal/spreg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: PySAL Spatial Econometrics Package
  description: |
    spreg, short for “spatial regression,” is a Python package to estimate
    simultaneous autoregressive spatial regression models. These models are
    useful when modeling processes where observations interact with one another.
    This package is part of a refactoring of PySAL.
  dev_url: https://github.com/pysal/spreg
  doc_url: https://github.com/pysal/spreg/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - pedrovma
    - jGaboardi
