{% set name = "spreg" %}
{% set version = "1.2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pysal/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2e6a46513d92820b020a3a96b002c4138364c0b8998386f3952dee9f2c6809db
  patches:
    - patches/0000-add_numpy_import.patch
    - patches/0001-remove-relative-imports-in-tests.patch
    - patches/0002-numpy-arrays-to-stack-must-be-list-or-tuple.patch
    - patches/0003-flatten-minimize-input.patch

build:
  number: 1
  # skip s390x libpysal not available in 4.10
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # libpysal: for py39 the version 4.5.1 will be used
    #           while >=4.10 is available only for py>39
    - libpysal
    - libpysal >=4.10  # [py>39]
    - numpy >=1.3
    - scipy >=0.11
    # scipy <1.12a0 for py39: ImportError: cannot import name 'inf' from 'scipy'
    - scipy >=0.11,<1.12a0  # [py<310]
    - pandas

test:
  imports:
    - spreg
  requires:
    - pip
    - pytest
  source_files:
    # tests not in the wheel
    - spreg/tests
  commands:
    - pip check
    # check that pip gets the correct version 
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Skip: 
    #     TestGMCombo::test_model "Not equal to tolerance rtol=1e-05, atol=0"
    # This problem is solved for newer versions of scipy which cannot be
    # used with python 3.9 (see comment above).
    - pytest -vv --deselect=spreg/tests/test_error_sp_sparse.py::TestGMCombo::test_model --deselect=spreg/tests/test_error_sp.py::TestGMCombo::test_model # [py<310]
    - pytest -vv  # [py>39]
about:
  home: https://github.com/pysal/spreg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: PySAL Spatial Econometrics Package
  description: |
    spreg, short for “spatial regression,” is a Python package to estimate
    simultaneous autoregressive spatial regression models. These models are
    useful when modeling processes where observations interact with one another.
    This package is part of a refactoring of PySAL.
  dev_url: https://github.com/pysal/spreg
  doc_url: https://github.com/pysal/spreg/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - pedrovma
    - jGaboardi
