travis:
  secure:
    BINSTAR_TOKEN: kBwHrhnIm/xYzU6WkPeqyL+naRbGOS1tAnxzBTgFBzvkTzdhedalwMKFE5qFiLmdfBxYpJ84oa1SWpGy/EVV1W82qrNDo7UMjlMDg63NG9GE4XEWP2+/jPwP0YyQ2A8O2PAR2c2+CiQG1f61ovChSOiJSprzUa86aTdcMNNcSAjah42+kHsY7i9kr7jPcbHEy1I+BM1xXSHoJMGgzTrWCj2i1k9Cyt7MKt2qc0ZYa8DeHPX/rzm6HE8JrnGIwwDdESWv0Y4OBZbYAOevzAbw2b9042HIkZBbaO+5HjiJykcrNBuEa79JmxWBo4vpBta+GUyFqDy6Dzu8PsVffndsp5atjvYMsO8e3TJxQqgod21Qdj9CiJPl/1dNpC5Angr7pn6+YMSRzaJglyjHeG/vGJNkRq/7txXaBEdTgtEzpMefMcsHIs3QNPYxlNamkb5mKUaoI//ciW5HcQliQgYUaOErwHd9oIQfAT9aStyl19RnXNpiYcCOufNyEKWVeGZDcJu04zhhILSI9LcFuZMcuDKoTpNeqisOUELpFpQYqhXcX4nOStXq6TBQ5HWwTI3Bcfknduu09ZJxp7OFHfVPuQzT4IdX9K8e4i0SLPP0v2xwQK9Q9Jqd7Rx3AMqBWDInDZH4nGMMPhy4LVFaESG7PQ8UH14yqcbxyG+z2dcISEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
